platform :ios, '8.0'


target ‘b2c_user_ios’ do

pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2’
pod 'Masonry', '~> 1.0.1’
pod 'MJRefresh', '~> 3.1.9’
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.8.1'

end  